import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';

// Presentation
const slides=[...document.querySelectorAll('.presentation-slide')];const dots=document.querySelector('#slideDots');let currentSlide=0;
function showSlide(i){if(!slides.length)return;currentSlide=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===currentSlide));document.querySelectorAll('.slide-dot').forEach((d,n)=>d.classList.toggle('active',n===currentSlide));const c=document.querySelector('#slideCounter');if(c)c.textContent=`SLIDE ${currentSlide+1} / ${slides.length}`}
if(slides.length&&dots)slides.forEach((_,i)=>{const d=document.createElement('button');d.className='slide-dot'+(i?'':' active');d.onclick=()=>showSlide(i);dots.appendChild(d)});
document.querySelector('#prevSlide')?.addEventListener('click',()=>showSlide(currentSlide-1));document.querySelector('#nextSlide')?.addEventListener('click',()=>showSlide(currentSlide+1));addEventListener('keydown',e=>{if(['ArrowRight','PageDown'].includes(e.key))showSlide(currentSlide+1);if(['ArrowLeft','PageUp'].includes(e.key))showSlide(currentSlide-1);if(e.key==='Home')showSlide(0);if(e.key==='End')showSlide(slides.length-1)});document.querySelector('#fullscreenPresentation')?.addEventListener('click',async()=>{if(!document.fullscreenElement)await document.querySelector('#presentation')?.requestFullscreen?.();else await document.exitFullscreen?.()});showSlide(0);

// Three.js game
const canvas=document.querySelector('#gameCanvas');const gameBox=canvas?.parentElement;const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fdcff);const camera=new THREE.PerspectiveCamera(65,1,.1,100);const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.shadowMap.enabled=true;const clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0xffffff,0x526040,2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(5,10,5);sun.castShadow=true;scene.add(sun);const world=new THREE.Group();scene.add(world);let kennel=false;const obstacles=[];
function box(x,y,z,sx,sy,sz,color,solid=true){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),new THREE.MeshStandardMaterial({color,roughness:.8}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;world.add(m);if(solid)obstacles.push({x,z,halfX:sx/2+.7,halfZ:sz/2+.7});return m}
function label(text,x,z){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='rgba(255,255,255,.92)';ctx.roundRect(8,8,496,112,24);ctx.fill();ctx.fillStyle='#30251f';ctx.font='bold 40px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,64);const t=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));s.position.set(x,3,z);s.scale.set(4,1,1);world.add(s)}
function resetWorld(){while(world.children.length)world.remove(world.children[0]);obstacles.length=0;box(0,-.15,0,22,.3,18,kennel?0x8b8b8b:0x78ad59,false);if(!kennel){box(0,1,-8.3,9,2,1,0xe7b77d);label('🏠 HONEY HOUSE',0,-7.2);box(-3,1,-4.8,2,1,.8,0xc48a55);label('🛋️ SOFA',-3,-4);box(4,.6,-4.8,2,1.2,1.2,0x7a4a28);label('🛏️ BED',4,-4);box(6,.5,1,1,1,1,0xe3a12e);label('🎾 TOYS',6,2);box(-6,.5,1,1,1,1,0xd97b2e);label('🦴 TREATS',-6,2);for(let i=0;i<6;i++){const trunk=box(-8+i*3,.8,5,.5,1.6,.5,0x76502d);const crown=new THREE.Mesh(new THREE.SphereGeometry(1.15,12,10),new THREE.MeshStandardMaterial({color:0x4f8e45}));crown.position.set(trunk.position.x,2.2,5);crown.castShadow=true;world.add(crown)}}else{box(0,1,-8.3,16,2,1,0x555555);box(-10.3,1,0,1,2,16,0x555555);box(10.3,1,0,1,2,16,0x555555);for(let x=-8;x<=8;x+=2){box(x,1,8.3,.15,2,.15,0x444444);box(x,1,-8.3,.15,2,.15,0x444444)}label('🔒 KENNEL AREA',0,-6);label('🍽️ FOOD / WATER',-5,1)}}resetWorld();

// Honey model
const honey=new THREE.Group();const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.8});
const body=new THREE.Mesh(new THREE.SphereGeometry(.82,24,16),mat(0xc9853d));body.scale.set(1.45,.9,.82);body.position.y=.45;body.castShadow=true;honey.add(body);const chest=new THREE.Mesh(new THREE.SphereGeometry(.62,20,14),mat(0xe2aa65));chest.scale.set(.75,1,.72);chest.position.set(.62,.45,0);chest.castShadow=true;honey.add(chest);const head=new THREE.Mesh(new THREE.SphereGeometry(.68,24,18),mat(0xd99a54));head.position.set(1.15,1.08,0);head.castShadow=true;honey.add(head);const muzzle=new THREE.Mesh(new THREE.SphereGeometry(.36,20,14),mat(0xf0c68a));muzzle.scale.set(1.2,.8,.8);muzzle.position.set(1.7,.93,0);honey.add(muzzle);const nose=new THREE.Mesh(new THREE.SphereGeometry(.13,16,12),mat(0x211914));nose.position.set(1.98,1.02,0);honey.add(nose);for(const z of[-.29,.29]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.075,12,10),mat(0x17110e));eye.position.set(1.48,1.3,z);honey.add(eye)}for(const z of[-.42,.42]){const ear=new THREE.Mesh(new THREE.ConeGeometry(.24,.6,12),mat(0x8d542d));ear.position.set(.98,1.65,z);ear.rotation.z=z>0?-.35:.35;ear.castShadow=true;honey.add(ear)}for(const z of[-.48,.48])for(const x of[-.45,.55]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.14,.17,.72,12),mat(0xa96331));leg.position.set(x,.05,z);leg.castShadow=true;honey.add(leg)}const tail=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.65,6,10),mat(0xb96f35));tail.position.set(-1.2,.65,0);tail.rotation.z=-.8;tail.castShadow=true;honey.add(tail);honey.position.set(0,.7,0);scene.add(honey);

// Mouse-look / pointer lock
let yaw=0,pitch=-.18,locked=false;const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')interact()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.addEventListener('click',()=>canvas.requestPointerLock?.());document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===canvas;const c=document.querySelector('.controls');if(c)c.textContent=locked?'WASD move • Mouse look • E interact • Esc releases mouse':'Click game to grab mouse • WASD move • Mouse look • E interact'});document.addEventListener('mousemove',e=>{if(!locked)return;yaw-=e.movementX*.0025;pitch-=e.movementY*.0025;pitch=THREE.MathUtils.clamp(pitch,-.6,.3)});

let happiness=90,fun=85,family=100;const msg=document.querySelector('#gameText');function updateUI(){for(const[id,v]of[['happiness',happiness],['fun',fun],['family',family]]){const value=document.querySelector('#'+id+'Value'),bar=document.querySelector('#'+id+'Bar');if(value)value.textContent=v;if(bar)bar.style.width=v+'%'}}function interact(){if(kennel){if(msg)msg.textContent='Honey looks around her smaller space. There is not much to interact with here.';return}if(msg)msg.textContent='Honey is having a great time with her family! ❤️';happiness=Math.min(100,happiness+4);fun=Math.min(100,fun+6);updateUI()}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(kennel){if(msg)msg.textContent='In this scenario, Honey has fewer activities available.';return}const a=b.dataset.action;const texts={toy:'Honey plays with her favourite toy! 🎾',food:'Honey gets a tasty treat! 🦴',walk:'Honey goes for a walk outside! 🌳',cuddle:'Honey gets lots of cuddles! ❤️'};if(msg)msg.textContent=texts[a];happiness=Math.min(100,happiness+4);fun=Math.min(100,fun+(a==='toy'||a==='walk'?8:2));family=Math.min(100,family+(a==='cuddle'?8:2));updateUI()});
function setMode(k){kennel=k;document.querySelector('#homeMode')?.classList.toggle('active',!k);document.querySelector('#kennelMode')?.classList.toggle('active',k);scene.background=new THREE.Color(k?0x737373:0x9fdcff);honey.position.set(0,.7,0);resetWorld();happiness=k?55:90;fun=k?35:85;family=k?20:100;if(msg)msg.textContent=k?'This is a simple game representation of a more restricted kennel routine—not a statement about every kennel.':'Honey is home with her family. Explore and interact!';updateUI()}
document.querySelector('#homeMode')?.addEventListener('click',()=>setMode(false));document.querySelector('#kennelMode')?.addEventListener('click',()=>setMode(true));
const fsBtn=document.querySelector('#fullscreenGame');fsBtn?.addEventListener('click',async()=>{if(!document.fullscreenElement)await gameBox?.requestFullscreen?.();else await document.exitFullscreen?.()});updateUI();
function blocked(x,z){return obstacles.some(o=>Math.abs(x-o.x)<o.halfX&&Math.abs(z-o.z)<o.halfZ)}
function resize(){const r=gameBox.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();

// W = forward, S = backward, A = left, D = right, based directly on the camera view.
function moveHoney(dt){let forward=0,strafe=0;if(keys.w)forward=1;if(keys.s)forward=-1;if(keys.a)strafe=-1;if(keys.d)strafe=1;if(!forward&&!strafe)return;
  // Use yaw directly so the controls cannot inherit a reversed X/Z axis from the model.
  // yaw=0 means the camera faces -Z, so W travels -Z.
  const forwardX=-Math.sin(yaw),forwardZ=-Math.cos(yaw);
  const rightX=Math.cos(yaw),rightZ=-Math.sin(yaw);
  let mx=forwardX*forward+rightX*strafe;let mz=forwardZ*forward+rightZ*strafe;const len=Math.hypot(mx,mz);if(len){mx/=len;mz/=len;}
  const speed=4;const nx=honey.position.x+mx*dt*speed,nz=honey.position.z+mz*dt*speed;
  if(!blocked(nx,honey.position.z))honey.position.x=THREE.MathUtils.clamp(nx,-8.4,8.4);if(!blocked(honey.position.x,nz))honey.position.z=THREE.MathUtils.clamp(nz,-7.7,7.7);
  // Honey's nose points along +X in the model, so rotate +X toward movement.
  honey.rotation.y=Math.atan2(mz,mx);
}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);moveHoney(dt);const target=honey.position.clone();const distance=7;const camX=target.x+Math.sin(yaw)*distance,camZ=target.z+Math.cos(yaw)*distance,camY=target.y+3.3+pitch*3;camera.position.lerp(new THREE.Vector3(camX,camY,camZ),.12);camera.lookAt(target.x,target.y+1,target.z);renderer.render(scene,camera)}
// Set an explicit starting camera so the first W press has a known forward direction.
camera.position.set(0,4.0,7);camera.lookAt(0,1,0);loop();